id: IE0037F57
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-02-02T17:40:27+00:00'
last_modified: '2022-06-10T10:28:06.550926+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC375
  title: 'རས་ཆུང་སྙན་བརྒྱུད་སྐོར། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    71A8:
      image_group_id: I4PD2758
      title: ''
      total_pages: 558
      order: 1
      base_file: 71A8.txt
    86F5:
      image_group_id: I4PD2759
      title: ''
      total_pages: 456
      order: 2
      base_file: 86F5.txt
    F641:
      image_group_id: I4PD2760
      title: ''
      total_pages: 406
      order: 3
      base_file: F641.txt
    4A92:
      image_group_id: I4PD2761
      title: ''
      total_pages: 418
      order: 4
      base_file: 4A92.txt
    F981:
      image_group_id: I4PD2762
      title: ''
      total_pages: 390
      order: 5
      base_file: F981.txt
    C0F3:
      image_group_id: I4PD2763
      title: ''
      total_pages: 374
      order: 6
      base_file: C0F3.txt
    8E79:
      image_group_id: I4PD2764
      title: ''
      total_pages: 386
      order: 7
      base_file: 8E79.txt
    4E22:
      image_group_id: I4PD2765
      title: ''
      total_pages: 358
      order: 8
      base_file: 4E22.txt
    BBAB:
      image_group_id: I4PD2766
      title: ''
      total_pages: 392
      order: 9
      base_file: BBAB.txt
    A888:
      image_group_id: I4PD2767
      title: ''
      total_pages: 384
      order: 10
      base_file: A888.txt
    583A:
      image_group_id: I4PD2768
      title: ''
      total_pages: 380
      order: 11
      base_file: 583A.txt
    '6376':
      image_group_id: I4PD2769
      title: ''
      total_pages: 358
      order: 12
      base_file: 6376.txt
    602F:
      image_group_id: I4PD2770
      title: ''
      total_pages: 370
      order: 13
      base_file: 602F.txt
    DD81:
      image_group_id: I4PD2771
      title: ''
      total_pages: 362
      order: 14
      base_file: DD81.txt
    EB02:
      image_group_id: I4PD2772
      title: ''
      total_pages: 338
      order: 15
      base_file: EB02.txt
    1DD7:
      image_group_id: I4PD2773
      title: ''
      total_pages: 412
      order: 16
      base_file: 1DD7.txt
    653A:
      image_group_id: I4PD2774
      title: ''
      total_pages: 388
      order: 17
      base_file: 653A.txt
    '9106':
      image_group_id: I4PD2775
      title: ''
      total_pages: 378
      order: 18
      base_file: 9106.txt
    E7AA:
      image_group_id: I4PD2776
      title: ''
      total_pages: 400
      order: 19
      base_file: E7AA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
